{
    'name': 'Health CMS Sidebar',
    'version': '19.0.1.2.0',
    'category': 'Healthcare',
    'summary': 'Unified sidebar for all healthcare centers (CRM, Operations, Finance, Admin)',
    'author': 'Biztinct',
    'depends': [
        'health_fieldservice',
        'health_crm',
        'health_invoicing',
        'health_landing',
        'health_flow',
        'access_roles',
        # Clinical spine + interop modules surfaced in the CLINICAL and
        # INTEROP & COMPLIANCE sidebar sections (their actions are referenced
        # by cms.sidebar.item.action_xmlid).
        'health_vitals',
        'health_careplan',
        'health_emar',
        'health_forms',
        'health_incident',
        'health_consent',
        'health_evv',
        'health_fhir_terminology',
        'health_fhir_adapter_base',
        'health_fhir_adapter_vn',
        'health_messaging',
    ],
    'data': [
        'security/health_cms_sidebar_security.xml',
        'security/ir.model.access.csv',
        'data/cms_sidebar_sections.xml',
        'data/cms_sidebar_items_crm.xml',
        'data/cms_sidebar_items_ops.xml',
        'data/cms_sidebar_items_ops_schedule.xml',
        'data/cms_sidebar_items_fin.xml',
        'data/cms_sidebar_items_admin.xml',
        'data/cms_sidebar_items_clinical.xml',
        'views/cms_sidebar_section_views.xml',
        'views/cms_sidebar_item_views.xml',
        'views/cms_sidebar_menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'health_cms_sidebar/static/src/scss/cms_sidebar.scss',
            'health_cms_sidebar/static/src/js/cms_sidebar.js',
            'health_cms_sidebar/static/src/xml/cms_sidebar.xml',
        ],
    },
    'installable': True,
    'application': False,
    'sequence': 140,
    'license': 'LGPL-3',
}
