{'name': 'Healthcare Base', 'version': '19.0.1.7.0', 'category': 'Healthcare', 'summary': 'Foundation module for VAFHS Healthcare Management System with Clinical Intelligence', 'description': '\nHealthcare Base Module v4.0\n===========================\n\nEnhanced foundation module for Vietnam-Australia Family Health Service (VAFHS) healthcare management system.\n\nKey Features:\n* Healthcare-specific data models and lookup codes\n* Vietnamese localization support\n* Professional mobile-responsive design\n* Multi-language support (Vietnamese & English)\n* Security and access controls\n* Clinical intelligence foundation\n', 'author': 'VAFHS Development Team', 'website': 'https://www.vafhs.com', 'license': 'LGPL-3', 'depends': ['base', 'hr', 'mail', 'portal', 'access_roles'], 'external_dependencies': {'python': ['requests']}, 'data': ['security/health_security.xml', 'security/ir.model.access.csv', 'security/catchment_global_rules.xml', 'data/health_data.xml', 'data/health_cancellation_reasons.xml', 'data/health_deletion_reasons.xml', 'data/health_facility_official.xml', 'data/res_country_state_data.xml', 'data/vietnamese_public_holidays.xml', 'data/health_catchment_province_data.xml', 'data/menu_access.xml', 'views/health_lookup_views.xml', 'views/health_lookup_value_views.xml', 'wizard/health_lookup_import_wizard_views.xml',
    # health_facility_views MUST load BEFORE health_catchment_province_views:
    # the province form carries a button referencing
    # %(health_base.action_health_facility)d, and the facility file is what
    # defines that action. Odoo resolves xmlids at load time, so on a FRESH
    # install the reverse order failed outright —
    #     ValueError: External ID not found in the system:
    #                 health_base.action_health_facility
    # An upgrade never showed it, because the action already existed from the
    # previous install. Found by the GC-3 CI gate, which installs from
    # scratch. Safe to swap: health_facility_views refers to the catchment
    # province only as a FIELD, never as an xmlid.
    'views/health_facility_views.xml',
    'views/health_catchment_province_views.xml',
    'views/health_patient_views.xml', 'views/resource_calendar_leaves_views.xml', 'views/health_audit_log_views.xml', 'views/res_users_views.xml', 'views/health_menus.xml', 'views/health_archive_log_views.xml', 'views/res_config_settings_views.xml', 'views/relationship_contact_popup_views.xml'], 'assets': {'web.assets_backend': ['health_base/static/src/css/health_base.css', 'health_base/static/src/css/notebook_icons.css', 'health_base/static/src/scss/patient_form_custom.scss', 'health_base/static/src/scss/center_dashboard_base.scss',
            'health_base/static/src/scss/statusbar_enhanced.scss',
            'health_base/static/src/scss/compact_density.scss',
            'health_base/static/src/scss/lifecycle_badges.scss', 'health_base/static/src/scss/chatter_bottom.scss', 'health_base/static/src/js/chatter_bottom.js', 'health_base/static/src/js/health_base.js', 'health_base/static/src/js/notebook_icons.js', 'health_base/static/src/js/address_autocomplete_widget.js', 'health_base/static/src/xml/address_autocomplete_widget.xml', 'health_base/static/src/scss/address_autocomplete_widget.scss', 'health_base/static/src/js/address_map_widget.js', 'health_base/static/src/xml/address_map_widget.xml', 'health_base/static/src/js/res_user_group_ids_checkboxes.js', 'health_base/static/src/components/relationship_hierarchy/relationship_hierarchy.js', 'health_base/static/src/components/relationship_hierarchy/relationship_hierarchy.xml', 'health_base/static/src/components/relationship_hierarchy/relationship_hierarchy.scss', 'health_base/static/src/js/address_dialog.js', 'health_base/static/src/xml/address_dialog.xml', 'health_base/static/src/scss/address_dialog.scss', 'health_base/static/src/js/archive_delete_policy.js', 'health_base/static/src/xml/lifecycle_buttons.xml'], 'web.assets_frontend': ['health_base/static/src/css/health_frontend.css']}, 'demo': ['demo/health_demo_data.xml'], 'installable': True, 'application': True, 'auto_install': False, 'sequence': 10, 'post_init_hook': 'post_init_hook'}
