from . import crm_lead
from . import res_partner
from . import res_partner_relation
from . import health_client_relation
from . import health_contact_reason
from . import health_lead_reason
from . import health_province
from . import crm_lead2opportunity_partner
from . import booking_lost_wizard