# -*- coding: utf-8 -*-
"""Single-use authorization attempts (architecture §5.3 / §7.3).

Everything the Zalo OAuth implementation got wrong (defect Z6: no PKCE, a
state that lives forever and is bound to nobody, a permanently persisted
authorization code, naive-vs-UTC expiry skew) is fixed structurally here:

* the random state is returned to the browser exactly once and stored **hashed**
  (gateway.token precedent) — a database reader cannot replay an attempt;
* PKCE S256 is generated by default and the verifier is encrypted at rest;
* the session expires after 10 minutes and is consumed **single-use**, with
  ``used_at`` stamped *before* any provider HTTP so a crash mid-exchange cannot
  leave a replayable state;
* unknown, used and expired states are indistinguishable to the caller — one
  generic outcome, no oracle;
* the redirect target is validated against an allowlist, so the callback can
  never be turned into an open redirect.

The callback *logic* lives here, in :meth:`_handle_callback`, rather than in
the controller: TransactionCase can then cover it end to end and the controller
stays a ten-line HTTP shell (ledger §5.32 — HttpCase side effects poison later
suites, so this module ships zero HttpCase).
"""
import base64
import hashlib
import logging
import secrets
from datetime import timedelta
from urllib.parse import urlparse

from odoo import _, api, fields, models
from odoo.exceptions import UserError

from ..services import channel_crypto
from ..services.redact import redact

_logger = logging.getLogger(__name__)

SESSION_TTL_MINUTES = 10
PURGE_AFTER_HOURS = 24

PROVIDERS = [
    ('meta', 'Meta'),
    ('zalo', 'Zalo'),
    ('google', 'Google'),
    ('microsoft', 'Microsoft'),
]

OUTCOMES = [
    ('pending', 'Pending'),
    ('ok', 'Completed'),
    ('denied', 'Denied by user'),
    ('expired', 'Expired'),
    ('error', 'Error'),
]

# Which platform provider a channel authorizes against. Channels absent from
# this map (telegram, call, webchat) have no OAuth flow at all; email is
# ambiguous (google vs microsoft) and must be passed explicitly.
CHANNEL_TO_PROVIDER = {
    'whatsapp': 'meta',
    'fb': 'meta',
    'zalo': 'zalo',
    'zns': 'zalo',
}


def _s256(verifier):
    """RFC 7636 code_challenge: base64url(sha256(verifier)), no padding."""
    digest = hashlib.sha256(verifier.encode('ascii')).digest()
    return base64.urlsafe_b64encode(digest).rstrip(b'=').decode('ascii')


class CareChannelOauthSession(models.Model):
    _name = 'care.channel.oauth.session'
    _description = 'Channel Authorization Session'
    _order = 'id desc'

    connection_id = fields.Many2one(
        'care.channel.connection', required=True, index=True,
        ondelete='cascade')
    company_id = fields.Many2one('res.company', required=True, index=True)
    user_id = fields.Many2one('res.users', required=True, index=True)
    provider = fields.Selection(PROVIDERS, required=True, index=True)
    state_hash = fields.Char(required=True, index=True)
    pkce_verifier_enc = fields.Text(groups='base.group_system')
    redirect_target = fields.Char()
    expires_at = fields.Datetime(required=True)
    used_at = fields.Datetime()
    outcome = fields.Selection(OUTCOMES, default='pending', required=True)
    detail_redacted = fields.Char(string='Detail')

    def init(self):
        # §5.1 — the hash lookup in _consume() depends on this being unique.
        self.env.cr.execute("""
            CREATE UNIQUE INDEX IF NOT EXISTS
                care_channel_oauth_session_state_hash_uniq
            ON care_channel_oauth_session (state_hash)
        """)

    # ------------------------------------------------------------------
    # Redirect allowlist (architecture §7.3)
    # ------------------------------------------------------------------
    @api.model
    def _allowed_redirect(self, url):
        """True when ``url`` is a safe post-authorization landing target.

        Relative paths are always fine. An absolute URL must point at our own
        base URL host or at a host explicitly listed in the
        ``channel_hub.allowed_redirect_hosts`` parameter (empty by default).
        Everything else is False — an open redirect on an OAuth callback is a
        credential-phishing primitive.
        """
        if not url:
            return True
        if not isinstance(url, str):
            return False
        if len(url) > 1 and url[0] == '/' and url[1] in ('/', '\\'):
            # Protocol-relative ('//host') or its backslash disguise
            # ('/\host' — browsers normalize \ to /): an absolute URL wearing
            # a relative costume (CC-A review finding #3).
            return False
        if url.startswith('/'):
            return True
        parsed = urlparse(url)
        if parsed.scheme not in ('http', 'https') or not parsed.netloc:
            return False
        icp = self.env['ir.config_parameter'].sudo()
        allowed = {urlparse(icp.get_param('web.base.url') or '').netloc}
        extra = icp.get_param('channel_hub.allowed_redirect_hosts') or ''
        allowed |= {h.strip() for h in extra.split(',') if h.strip()}
        allowed.discard('')
        return parsed.netloc in allowed

    # ------------------------------------------------------------------
    # Create / consume
    # ------------------------------------------------------------------
    @api.model
    def create_for(self, connection, redirect_target=None, provider=None,
                   use_pkce=True):
        """Open an authorization attempt.

        Returns ``{'session_id', 'state', 'code_challenge',
        'code_challenge_method'}`` — the ONLY time the raw state or the PKCE
        challenge leaves the server.
        """
        connection.ensure_one()
        provider = provider or CHANNEL_TO_PROVIDER.get(connection.channel)
        if not provider:
            raise UserError(_(
                'This channel is not connected by signing in with a provider.'))
        if not self._allowed_redirect(redirect_target):
            # Fixed string: never echo the rejected URL back to the caller.
            raise UserError(_('That return address is not allowed.'))
        state = secrets.token_urlsafe(32)
        vals = {
            'connection_id': connection.id,
            'company_id': connection.company_id.id,
            'user_id': self.env.uid,
            'provider': provider,
            'state_hash': hashlib.sha256(state.encode('utf-8')).hexdigest(),
            'redirect_target': redirect_target or False,
            'expires_at': fields.Datetime.now() + timedelta(
                minutes=SESSION_TTL_MINUTES),
        }
        challenge = False
        if use_pkce:
            verifier = secrets.token_urlsafe(64)
            challenge = _s256(verifier)
            vals['pkce_verifier_enc'] = channel_crypto.encrypt(self.env, verifier)
        session = self.sudo().create(vals)
        self.env['care.channel.audit']._log(
            'connect_start', connection=connection,
            detail='provider %s' % provider)
        return {
            'session_id': session.id,
            'state': state,
            'code_challenge': challenge,
            'code_challenge_method': 'S256' if challenge else False,
        }

    @api.model
    def _consume(self, state):
        """Look a state up by hash and burn it. Returns the session or None.

        Unknown, already-used and expired all return ``None`` — the caller
        cannot tell them apart, so the endpoint is not an oracle for guessing
        valid states. ``used_at`` is stamped in the same transaction, BEFORE
        any provider call, so a failure later in the exchange still leaves the
        state single-use.
        """
        if not state or not isinstance(state, str):
            return None
        digest = hashlib.sha256(state.encode('utf-8')).hexdigest()
        session = self.sudo().search([('state_hash', '=', digest)], limit=1)
        if not session or session.used_at:
            return None
        if session.expires_at and session.expires_at < fields.Datetime.now():
            session.write({'outcome': 'expired', 'used_at': fields.Datetime.now()})
            return None
        session.write({'used_at': fields.Datetime.now()})
        return session

    def _get_pkce_verifier(self):
        """Server-side only (leading underscore ⇒ not RPC-callable)."""
        self.ensure_one()
        return channel_crypto.decrypt(self.env, self.sudo().pkce_verifier_enc or '')

    # ------------------------------------------------------------------
    # Callback logic (the controller is a shell around this)
    # ------------------------------------------------------------------
    @api.model
    def _handle_callback(self, provider, params):
        """Process one provider redirect.

        Returns ``{'outcome', 'ok', 'channel'}``. ``outcome`` is one of
        ``generic`` (unknown/used/expired/mismatched — a single indistinguish-
        able bucket), ``denied`` (the user said no), ``error`` or ``ok``.
        Nothing from ``params`` is ever returned or rendered.
        """
        generic = {'outcome': 'generic', 'ok': False, 'channel': False}
        params = params or {}
        session = self._consume(params.get('state'))
        if not session:
            return generic
        connection = session.connection_id
        if session.provider != provider:
            session.write({'outcome': 'error',
                           'detail_redacted': 'provider mismatch'})
            self.env['care.channel.audit']._log(
                'callback_error', connection=connection,
                detail='provider mismatch')
            return generic
        if params.get('error') or params.get('error_code') or params.get('denied'):
            session.write({
                'outcome': 'denied',
                'detail_redacted': redact(params.get('error_description')
                                          or params.get('error')
                                          or 'denied'),
            })
            self.env['care.channel.audit']._log(
                'callback_denied', connection=connection, detail='user denied')
            return {'outcome': 'denied', 'ok': False,
                    'channel': connection.channel}
        try:
            with self.env.cr.savepoint():
                result = connection.sudo()._get_adapter().handle_callback(
                    session, params)
        except NotImplementedError:
            # CC-A ships declaration-only adapters: the framework works, the
            # provider exchange lands in CC-D/CC-E/CC-F.
            session.write({'outcome': 'error',
                           'detail_redacted': 'adapter not implemented'})
            self.env['care.channel.audit']._log(
                'callback_error', connection=connection,
                detail='adapter not implemented')
            return {'outcome': 'error', 'ok': False,
                    'channel': connection.channel}
        except Exception as exc:  # noqa: BLE001 — provider/network failure
            session.write({'outcome': 'error', 'detail_redacted': redact(exc)})
            self.env['care.channel.audit']._log(
                'callback_error', connection=connection, detail=exc)
            return {'outcome': 'error', 'ok': False,
                    'channel': connection.channel}
        session.write({'outcome': 'ok'})
        self.env['care.channel.audit']._log(
            'callback_ok', connection=connection,
            detail=(result or {}).get('next_step') if isinstance(result, dict) else None)
        return {'outcome': 'ok', 'ok': True, 'channel': connection.channel}

    # ------------------------------------------------------------------
    # Purge cron
    # ------------------------------------------------------------------
    @api.model
    def _cron_purge_oauth_sessions(self):
        cutoff = fields.Datetime.now() - timedelta(hours=PURGE_AFTER_HOURS)
        stale = self.sudo().search([('create_date', '<', cutoff)])
        count = len(stale)
        if count:
            stale.unlink()
            _logger.info('Purged %s expired channel authorization session(s)', count)
        return count
