from . import health_fieldservice_order
from . import health_fieldservice_stage
from . import health_fieldservice_team
from . import health_portable_equipment
from . import health_clinical_protocol
from . import health_fieldservice_communication
from . import health_staff_assignment
from . import health_ai_assignment_engine
from . import health_staff_availability
from . import healthcare_skill
from . import hr_employee
from . import res_partner